version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    depends_on: 
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app  
  db:
    image: mongo:latest
    restart: always
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - /usr/local/var/mongodb:/data 
  